[workspace]
members = [ "apps", "octets", "qlog", "quiche" ]
exclude = [ "fuzz", "tools/http3_test" ]

[profile.bench]
debug = true

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
